### ISSUE TITLE
Inquiry about deprecated Request package

### ISSUE THREAD

**Issue by farnaz-rashidi** [Moesif/moesifapi-nodejs#24]
Hello there,

I have `moesifapi` installed in my project as a transitive dependency and I noticed that `npm audit` throws warnings about a moderate vulnerability in the `request` package which is a direct dependency of `moesifapi`. 

The vulnerability is documented here: [[GHSA-p8p7-x288-28g6]](https://github.com/advisories/GHSA-p8p7-x288-28g6).

Since the `request` package has been deprecated, I was wondering if you have any plans on replacing it and/or taking any other measures to mitigate the risk?

Thank You,

**Comment by dgilling** [comment]
Hi @farnaz-rashidi , we reviewed the vulnerability. The only host that the Moesif lib communicates with is `api.moesif.net` which also doesn't do any redirects so the risk for this lib is low/not relevant. With that said, we have a ticket open to update and verify the dependencies. Thanks for bringing this to our attention.

**Comment by praves77** [comment]
@farnaz-rashidi `fyi` We've released [v2.1.1](https://github.com/Moesif/moesifapi-nodejs/releases/tag/v2.1.1) to address it.

**Comment by farnaz-rashidi** [comment]
Thanks team 🙌.
