### ISSUE TITLE
moesif-nodejs: error parsing config

### ISSUE THREAD

**Issue by igrek8** [Moesif/moesifapi-nodejs#27]
[`event.response.body` is an object](https://github.com/Moesif/moesif-nodejs/blob/master/lib/moesifConfigManager.js#L47). Attempting to parse it as JSON results in exception: `SyntaxError: Unexpected token d in JSON at position 0`. Maybe related to the PR - [convert-response-data-into-body](https://github.com/Moesif/moesifapi-nodejs/tree/convert-response-data-into-body)

<img width="591" alt="image" src="https://github.com/Moesif/moesifapi-nodejs/assets/7078731/40d9cc79-cc78-48f3-a3be-6daa166307e2">

**Comment by xinghengwang** [comment]
sorry about that plase. update to 3.4.3
