### ISSUE TITLE
TypeError: axios is not a function

### ISSUE THREAD

**Issue by cjayprime** [Moesif/moesifapi-nodejs#46]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `moesifapi@3.1.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/moesifapi/lib/Http/Client/RequestClient.js b/node_modules/moesifapi/lib/Http/Client/RequestClient.js
index 2f3c0b3..2dc0439 100644
--- a/node_modules/moesifapi/lib/Http/Client/RequestClient.js
+++ b/node_modules/moesifapi/lib/Http/Client/RequestClient.js
@@ -1,7 +1,7 @@
 var HttpContext = require("./HttpContext");
 var HttpResponse = require("../Response/HttpResponse");
 var https = require("https");
-var axios = require("axios");
+var axios = require("axios").default;
 var axiosRetry = require("axios-retry");
 var zlib = require("zlib");
 var APIHelper = require("../../APIHelper");
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by xinghengwang** [comment]
thanks for the reporting the issue.

**Comment by xinghengwang** [comment]
https://github.com/Moesif/moesifapi-nodejs/releases/tag/v3.1.2
